cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),

]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns
# from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('django.contrib.auth.urls')),
    path('social_auth/', include('social_django.urls', namespace='social')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'order'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path(_('apply/'), views.coupon_apply, name='apply'),
    path('admin/order/<int:order_id>', views.admin_order_detail, name='admin_order_detail'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('<slug:category_slug>/', views.item_list, name='item_list'),
    path('<int:id>/<slug:slug>/', views.item_detail, name='item_detail'),
]

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

ITEM_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddItemForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=ITEM_QUANTITY_CHOICES,
                                      coerce=int,
                                      label=_('Quantity'))

    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Item
from shop.recommender import Recommender
from coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddItemForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@require_POST
def cart_add(request, item_id):
    cart = Cart(request)
    item = get_object_or_404(Item, id=item_id)
    cart.add(item=item)
    messages.info(request, "Item added to cart")
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, item_id):
    cart = Cart(request)
    item = get_object_or_404(Item, id=item_id)
    cart.remove(item)
    messages.info(request, "Item removed from cart")
    if cart:
        return redirect('cart:cart_detail')
    return redirect('/')


@login_required
def cart_detail(request):
    cart = Cart(request)
    for product in cart:
        product['update_quantity_form'] = CartAddItemForm(initial={
            'quantity': product['quantity'],
            'override': True
        })
    coupon_apply_form = CouponApplyForm()

    r = Recommender()
    cart_products = [product['item'] for product in cart]
    recommended_products = r.suggest_product_for(cart_products, max_result=4)

    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form,
                   'recommended_products': recommended_products})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Your shopping cart" %}{% endblock %}

{% block content %}
<main class="mt-3 pt-3">
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="shopping__cart__table">
                        <table class="table-responsive">
                            <thead>
                                <tr>
                                    <th>{% trans "Product" %}</th>
                                    <th>{% trans "Quantity" %}</th>
                                    <th>{% trans "Total" %}</th>
                                    <th style="padding-left:15px">{% trans "Remove" %}</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody class="tbody-responsive">
                            {% for product in cart %}
                            {% with item=product.item %}
                                <tr>
                                    <td class="product__cart__item">
                                        <div class="product__cart__item__pic">
                                            <img src="{{ item.image.url }}" alt="" width="100" height="100">
                                        </div>
                                        <div class="product__cart__item__text">
                                            <h6>{{ item.name }}</h6>
                                            <h5>${{ item.price }}</h5>
                                        </div>
                                    </td>
                                    </td>
                                    <td>
                                        <form class="d-flex justify-content-left" action="{% url "cart:cart_add" item.id %}" method="post" style="width:100%">
                                        {{ product.update_quantity_form.quantity }}
                                        {{ product.update_quantity_form.override }}
                                        <button class="btn btn-primary btn-md my-0 p">{% trans "Update" %}</button>
                                        {% csrf_token %}
                                        </form>
                                    </td>
                                        <td class="num" style="font-weight:600; font-size: 18px;">${{ product.total_price }}</td>
                                        <td>
                                            <form action="{% url "cart:cart_remove" item.id %}" method="post">
                                                <button class="close fas fa-times-circle" style="font-size: 40px"> </button>
                                                {% csrf_token %}
                                            </form>
                                        </td>
                                    </tr>
                            {% endwith %}
                            {% endfor %}
                            </tbody>
                        </table>
                        <br>

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="cart__discount">
                        <h6><strong>DISCOUNT CODES  <i class="fas fa-ticket-alt" style="font-size: 20px"></i></strong></h6>
                        <form action="{% url "coupons:apply" %}" method="post">
                            <div class="input-group">
                                <input type="text" id="code" name="code" class="form-control" placeholder="Coupon code">
                                {% csrf_token %}
                                <div class="input-group-append">
                                    <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">{% trans "Redeem" %} <i class="fas fa-gift" style="font-size: 15px"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="cart__total">
                        <h6 style="font-weight: 900;">Cart total<i class="fa fa-shopping-cart"></i></h6>
                        <ul>
                            <li style="font-weight: 600;">{% trans "Subtotal" %}
                                <span>$ {{ cart.get_total_price }}</span>
                            </li>
                            {% if cart.coupon %}
                            <li>"{{cart.coupon.code}}" {% trans "coupon" %}
                                ({{ cart.coupon.discount }}% {% trans "off" %}) <span>-$ {{ cart.get_discount|floatformat:2 }}</span>
                            </li>
                            {% endif %}
                            <li style="font-weight: 800;">{% trans "TOTAL" %} <span>$ {{ cart.get_total_price_after_discount|floatformat:2 }}</span></li>
                        </ul>
                    </div>
                    <br>
                    <div class="row d-flex justify-content-center">
                            <div class="col">
                                <a href="{% url "shop:item_list" %}"><button class="btn btn-primary btn-md my-0 p" style="padding-left:12px; padding-right:12px">{% trans "Continue shopping" %}</button></a>
                            </div>

                        <div class="col">
                            <a href="{% url "orders:order_create" %}"><button class="btn btn-secondary btn-md my-0 p">{% trans "Checkout" %}<i class="fa fa-shopping-cart"></i></button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if recommended_products %}
    <section class="related spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="related-title">Related Product</h3>
                </div>
            </div>
            <div class="row">
                {% for p in recommended_products %}
                <div class="col-lg-3 col-md-6 col-sm-6 col-sm-6">
                    <div class="card" style="height: 16rem; width: 12rem">
                        <div class="view overlay">
                            <a href="{{ p.get_absolute_url }}">
                                <img src="{{ p.image.url }}" class="card-img-top" alt="">
                            </a>
                        </div>
                        <div class="card-body" style="height: 2rem">
                            <p style="font-size: 15px; font-weight: 900;"><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
    </section>
</main>
{% endblock %}