cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),

]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns
# from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('django.contrib.auth.urls')),
    path('social_auth/', include('social_django.urls', namespace='social')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'order'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path(_('apply/'), views.coupon_apply, name='apply'),
    path('admin/order/<int:order_id>', views.admin_order_detail, name='admin_order_detail'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('<slug:category_slug>/', views.item_list, name='item_list'),
    path('<int:id>/<slug:slug>/', views.item_detail, name='item_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse

# CATEGORY_CHOICES = (
#     ('AR', 'Arts and Crafts'),
#     ('AU', 'Automotive'),
#     ('B', 'Baby'),
#     ('BP', 'Beauty and personal care'),
#     ('BK', 'Books'),
#     ('CM', 'Computers'),
#     ('DM', 'Digital music'),
#     ('E', 'Electronics'),
#     ('W', 'Women\'s fashion'),
#     ('M', 'Men\'s fashion'),
#     ('G', 'Girl\'s fashion'),
#     ('BY', 'Boy\'s fashion'),
#     ('HH', 'Health and household'),
#     ('HK', 'Home and kitchen'),
#     ('ID', 'industrial and scientific'),
#     ('L', 'Luggage'),
#     ('MT', 'Movies and Tv'),
#     ('S', 'Software'),
#     ('SO', 'Sports and outdoor'),
#     ('TH', 'Tools and Home improvement'),
#     ('TG', 'Toys and games'),
#     ('VG', 'Video games and accessories')
#                     )

LABEL_CHOICES = (
    ('S', 'secondary'),
    ('P', 'primary'),
    ('D', 'danger'),
)

TAG_CHOICES = (
    ('Best Seller', 'Best Seller'),
    ('NEW', 'NEW'),
    ('HOT', 'HOT')
)


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:item_list',
                       args=[self.slug])


class Item(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = models.CharField(choices=TAG_CHOICES,
                            max_length=20, blank=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:item_detail',
                       args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Item
from .recommender import Recommender
from cart.views import CartAddItemForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required


def item_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    items = Item.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        items = items.filter(category=category)

    paginator = Paginator(items, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request,
                  'item/list.html',
                  {'category': category,
                   'categories': categories,
                   'page_obj': page_obj,
                   'items': items})


def item_detail(request, id, slug):
    item = get_object_or_404(Item,
                             id=id,
                             slug=slug,
                             available=True)
    cart_item_form = CartAddItemForm

    r = Recommender()
    recommended_products = r.suggest_product_for([item], 4)

    return render(request,
                  'product-page.html',
                  {'item': item,
                   'cart_item_form': cart_item_form,
                   'recommended_products': recommended_products})

shop/templates/checkout-page.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block content %}
<body class="grey lighten-3">

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form class="card-body" method="POST">

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--firstName-->
                  <div class="md-form ">
                    {{ form.first_name.as_p }}
                    <input type="text" id="first_name" name="first_name" class="form-control">
                    <label for="first_name" class="">First name</label>
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--lastName-->
                  <div class="md-form">
                    {{ form.last_name.as_p }}
                    <input type="text" id="last_name" name="last_name" class="form-control">
                    <label for="last_name" class="">Last name</label>
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <!--email-->
              <div class="md-form mb-5">
                {{ form.email.as_p }}
                <input type="text" id="email" name="email" class="form-control" placeholder="youremail@example.com">
                <label for="email" class="">Email (optional)</label>
              </div>

              <!--address-->
              <div class="md-form mb-5">
                {{ form.address.as_p }}
                <input type="text" id="address" name="address" class="form-control" placeholder="1234 Main St">
                <label for="address" class="">Address</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  {{ form.country.as_p }}
                  <input type="text" id="country" name="country" class="form-control" placeholder="United states">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="city">State</label>
                  {{ form.city.as_p }}
                  <input type="text" id="city" name="city" class="form-control" placeholder="California">
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="postal_code">Zip</label>
                  {{ form.postal_code.as_p }}
                  <input type="text" class="form-control" id="postal_code" name="postal_code" placeholder="" required>
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->
              {% csrf_token %}
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{ cart|length }}</span>
          </h4>
          {% for product in cart %}
          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0"><span class="badge badge-secondary badge-pill">{{ product.quantity }}</span>
                  <strong>{{ product.item.name }}</strong></h6>
                <small class="text-muted">{{ product.item.description|truncatechars:40 }}</small>
              </div>
              <span class="text-muted">${{ product.item.price }}</span>
            </li>
            {% endfor %}

            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-1">Coupon code:</h6>
                <strong>"{{ cart.coupon.code }}" ({{ cart.coupon.discount }}% off)</strong>
              </div>
              <span class="text-success">- ${{ cart.get_discount|floatformat:2 }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${{ cart.get_total_price_after_discount|floatformat:2 }}</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
                  <form action="{% url "orders:apply" %}" method="post" class="card p-2">
                    <div class="input-group">
                        {{ coupon_apply_form.as_bootstrap }}
                      <input type="text" id="code" name="code" class="form-control" placeholder="Promo code">
                         {% csrf_token %}
                      <div class="input-group-append">
                        <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                      </div>
                    </div>
                  </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock %}

shop/templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

shop/templates/product-page.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "product page" %}{% endblock %}

{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ item.image.url|default_if_none:'https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/14.jpg' }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">
            <div class="product-detail">
              <strong><b>
              <h2 class="dark-grey-text" class="lead font-weight-bold" style="font-weight:700;">{{ item.name }}</h2>
              </b>
              </strong>
            </div>

            <div class="mb-3">
              <a href="{{ item.category.get_absolute_url }}">
                <span class="badge purple mr-1">{{ item.category }}</span>
              </a>
              <a href="">
                <span class="badge {{ item.get_label_display }}-color">{{ item.tags }}</span>
              </a>

            <h3 class="lead">
                {% if item.discount_price %}
                <span class="mr-1">
                    <span><del>${{ item.price }}</del></span>
                    <span style="font-weight:600">${{ item.discount_price }}</span>
                    {% else %}
                    <br>
                    <span style="font-weight: 800;">${{ item.price }}</span>
                </span>
                {% endif %}
            </h3>

            <p class="lead font-weight-bold">{% trans "Description" %}</p>

            <p>{{ item.description }}</p>

            <form class="d-flex justify-content-left" action="{% url "cart:cart_add" item.id %}" method="post">
<!--              &lt;!&ndash; Default input &ndash;&gt;-->
<!--              {{ cart_item_form }}-->
              {% csrf_token %}
              <button class="btn btn-primary btn-md my-0 p" type="submit">{% trans "Add to cart" %}
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
<!--      <div class="row d-flex justify-content-center wow fadeIn">-->

        <!--Grid column-->
<!--        <div class="col-md-6 text-center">-->

<!--          <h4 class="my-4 h4">Additional information</h4>-->

<!--          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit-->
<!--            voluptates,-->
<!--            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>-->

<!--        </div>-->
<!--        &lt;!&ndash;Grid column&ndash;&gt;-->

      </div>
      <!--Grid row-->
      {% if recommended_products %}
    <section class="related spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="related-title">Related Product</h3>
                </div>
            </div>
            <div class="row">
                {% for p in recommended_products %}
                <div class="col-lg-3 col-md-6 col-sm-6 col-sm-6">
                    <div class="card " style="height: 18rem; width: 12rem">
                        <div class="view overlay">
                            <a href="{{ p.get_absolute_url }}">
                                <img src="{{ p.image.url }}" class="card-img-top" alt="">
                            </a>
                        </div>
                        <div class="card-body text-center" style="height: 3rem">
                            <p style="font-size: 16px; font-weight: 900;"><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
        </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

</body>
{% endblock %}

</html>